# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# Check https://fabricmc.net/versions.html for the latest versions.
minecraft_version=1.21.6
yarn_mappings=1.21.6+build.1
loader_version=0.16.14
fabric_kotlin_version=1.13.0+kotlin.2.1.0

# Mod Properties
mod_version=1.0.0
maven_group=milk.creeper
archives_base_name=creepermilk

# Dependencies
fabric_version=0.128.2+1.21.6

# For more information, see https://docs.gradle.org/current/userguide/toolchains.html
java.toolchain = 21
loom.toolchain = 21

# Set the configurations for your run configurations.
# Reference: https://github.com/FabricMC/fabric-loom/blob/dev/1.6/README.md#configuring-run-configurations
# Loom will automatically configure the client and server run configurations.
# You can add more run configurations here.
loom.runs {
    # This is the default client run configuration.
    client {
        ideConfigGenerated = true
        runDir = "run/client"
        source(sourceSets.main)
        source(sourceSets.client)
    }
    # This is the default server run configuration.
    server {
        ideConfigGenerated = true
        runDir = "run/server"
        source(sourceSets.main)
    }
    # This is a run configuration for data generation.
    data {
        ideConfigGenerated = true
        runDir = "run/data"
        source(sourceSets.main)
        vmArg "-Dfabric-api.datagen"
        vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
        vmArg "-Dfabric-api.datagen.modid=creepermilk"
    }
}